# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 858bd49b2dda7e44a741141f18445f43a4163778f513ba2a8da7b9a69c96ec8ba9a68095167c3d7f75396526997b94bf49c4a29b32b9adde8415ca16d829b6d6

test:
  secret_key_base: cf61c57c398e09de9c8a7ca6fd00dc646c2c82f1f8877e46ff112aaba89e7d1102543699e60d3474dc27f3d761152221920cd34ecec35c157ff012e7fa4a102e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
